### PR TITLE
Email and other bugfixes

### LINKED ISSUE #76: Activate Unsubscribe in email notificaitons
By law, users must be able to unsubscribe to email notifications from food shift. The email template currently has an 'unsubscribe' link but it doesn't work. Make it work!

### PR DESCRIPTION
**Pull request by jjwon**
After a millennia of struggling with heroku (sorry for all the commit inflation, I was deploying off of github when I should probably just have pushed straight to heroku), Jason Productions presents:

#### Table of Contents
- Setting up both a new development Heroku app
- Sending emails to subscribed recipients only
- Adding endpoint for one-click unsubscribe
- Adding secret tokens to users
- Cleaning up CanCanCan permissions that didn't make sense
- More informative alerts
- Landing images moved to S3
- Learning that you can't use ActionMailer to send emails on Heroku (?!?!!?)
- Using SendGrid in production heroku
- Procfile using thin for production heroku

Resolves #76, #67

### CODE REVIEW

File: config/environments/production.rb [hunk 1]
```diff
@@ -64,6 +64,14 @@
   # Ignore bad email addresses and do not raise email delivery errors.
   # Set this to true and configure the email server for immediate delivery to raise delivery errors.
   # config.action_mailer.raise_delivery_errors = false
+  config.action_mailer.smtp_settings = {
+    address:              "smtp.sendgrid.net",
```
Comment (jjwon) [inline config/environments/production.rb]: stfu this is more legible hound-- :-1:
